[package]
name = "secret"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-log.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
target.path = "../../wit/trinity-module.wit"
